Feature denisarger 20
hiscoder-com/glokas pull request #35
Opened 2024-10-14 12:06 UTC by DenisArger

#20 - add components YouTubeCard and  YoutubeParserModal

2024-10-15 07:26 UTC, Valyukhov commented on app/components/YouTubeCard.jsx
> +    <div className="flex h-64 w-64 flex-col items-center justify-center rounded-3xl border border-[#C9DFFC] bg-[#EFF5FE] shadow-lg">
`shadow-lg` - я не увидел в дизайне тень

2024-10-15 08:15 UTC, Valyukhov reviewed
часть замечаний

2024-10-15 08:15 UTC, Valyukhov commented on app/components/YouTubeCard.jsx
> +    <div className="flex h-64 w-64 flex-col items-center justify-center rounded-3xl border border-[#C9DFFC] bg-[#EFF5FE] shadow-lg">
цвета тоже надо брать nextui, чтобы в одном месте все менялись

2024-10-15 08:15 UTC, Valyukhov commented on app/components/YoutubeParserModal.jsx
> +      <button className="rounded-md bg-primary px-4 py-2 text-white" onClick={openModal}>
цвет текста брать из nextui

2024-10-15 10:44 UTC, Valyukhov commented on app/components/YoutubeParserModal.jsx
> +                alt="YouTube"
в дизайне меньше 
![image](https://github.com/user-attachments/assets/93bd41af-6048-4ce0-8f0f-b7072d33aa25)

2024-10-15 11:04 UTC, Valyukhov commented on app/components/YoutubeParserModal.jsx
> +              <button
надо взять CustomButton, там есть параметры disabled, ты нарисовал только одно состояние кнопки

2024-10-15 11:57 UTC, Valyukhov commented on app/components/YoutubeParserModal.jsx
> +          <div className="relative h-[46vh] w-[40vw] rounded-2xl bg-white p-[52px]">
![image](https://github.com/user-attachments/assets/eabe02e7-403f-4398-a9c8-9ea909a45728)
у меня отступы не по дизайну показывает, может стоит минимальную высоту задать?
`min-h-`

2024-10-15 12:00 UTC, Valyukhov commented on app/components/YoutubeParserModal.jsx
> +              <input
CustomInput возьми, там возможно будет состояние ошибки

2024-10-15 12:00 UTC, Valyukhov reviewed
Проверил, есть комментарии

2024-10-17 11:36 UTC, foxprogs requested changes

2024-10-17 11:36 UTC, foxprogs commented on app/components/YoutubeParserModal.jsx
> +              className="max-h-32 overflow-y-auto rounded-xlarge bg-tertiary-100 p-4 text-medium text-tertiary-700 md:text-large" // prettier-ignore
max-h-32 overflow-y-auto вот так не надо делать. Скролл уже есть у самой модалки.

2024-10-17 11:36 UTC, foxprogs commented on app/components/YoutubeParserModal.jsx
> +              ipsum faucibus. Porttitor et nisi aenean id dui risus quis nunc ut.
Надо или спросить, что за текст тут должен быть, и сразу заменить на правильный. Или добавить TODO чтобы такое в прод не полетело.

2024-10-17 11:36 UTC, foxprogs commented on app/components/YoutubeParserModal.jsx
> +              className="max-h-32 overflow-y-auto rounded-xlarge bg-tertiary-100 p-4 text-medium text-tertiary-700 md:text-large" // prettier-ignore
font-weight: 500 по дизайну

2024-10-17 11:36 UTC, foxprogs commented on app/components/YoutubeParserModal.jsx
> +                  description=" Example: https://www.youtube.com/watch?v=Dl56yoDQAJc"
а что за лишний пробел?

2024-10-17 11:36 UTC, foxprogs commented on app/components/YoutubeParserModal.jsx
![изображение](https://github.com/user-attachments/assets/8e295721-c2cb-4704-9b3e-c8487c983837)
![изображение](https://github.com/user-attachments/assets/f891e8dd-7ce6-4b52-a015-aa4d2995fce5)
Кнопка по размеру отличается, цвета красный отличаются, у инпута нет ! знака, у Паши это есть

2024-10-17 11:36 UTC, foxprogs commented on app/components/YoutubeParserModal.jsx
> +            <button
![изображение](https://github.com/user-attachments/assets/39f71eff-c7fe-49c7-9153-dd8d2632bca0)
крестик уходит

2024-10-17 11:36 UTC, foxprogs commented on app/components/YoutubeParserModal.jsx
> +      console.log(`Parsed URL: ${youtubeUrl}`)
надо айдишник возвращать а не весь юрл

2024-10-17 11:36 UTC, foxprogs commented on app/components/YoutubeParserModal.jsx
![изображение](https://github.com/user-attachments/assets/b20ab626-7ed6-42dc-8096-e34a248f6385)
вот тут текст не больше чем кнопка, у нее получается фикс размер что ли?

2024-10-21 18:46 UTC, foxprogs requested changes

2024-10-21 18:46 UTC, foxprogs commented on app/components/YoutubeParser.tsx
> +      /^https?:\/\/(?:www\.)?(?:youtube\.com\/watch\?v=|youtu\.be\/)([\w-]{11})$/
регулярка не покрывает все возможные варианты ссылок. 
К примеру бывает вот такое 
https://youtu.be/PiMr3M42UN0?si=4N43v5om9dCMt5Ch
И еще с десяток вариантов. 
В гугле легко найти варианты, котоыре бывают у ссылок, и так же регулярку.

2024-10-21 18:46 UTC, foxprogs commented on app/components/YoutubeParser.tsx
> +          <div className="relative max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-secondary-foreground px-16 pb-16 pt-[52px]">
и вот этот див, мне кажется часть классов тут точно можно перенести в модалку. К примеру в модалке же уже есть скругление, и высота указана. То есть тут дублируются классы. И 52px я бы заменил все же. В другом типе модалки к примеру 48. Может и тут тоже.

2024-10-21 18:46 UTC, foxprogs commented on tailwind.config.js
> +        xxxxlarge: '1,125rem', // rounded-xxxxlarge
сбился, в скольких пр написал про то чтобы это удалить и заменить)

2024-10-21 18:46 UTC, foxprogs commented on tailwind.config.js
boxShadow надо настроить. Я посмотрел в дизайне, есть всего две тени. Одна у модалки и вторая у тултипа. По этому надо настроить тут. Сейчас у модалки совсем не та тень, которая в фигме.

2024-10-21 18:46 UTC, foxprogs commented on app/components/Modal.tsx
> +      <div className={`relative my-6 max-h-[90vh] rounded-2xl shadow-medium`}>
тень не та, и надо настроить модалку: ширину, фон, скролл, отступы внутри и снаружи.

2024-10-21 18:46 UTC, foxprogs commented on app/components/Modal.tsx
>            className={`absolute right-5 top-5 h-11 w-11 items-center justify-center p-3 text-black`}
мне сейчас не видно этот крестик

2024-10-22 07:35 UTC, DenisArger commented on app/(web)/page.tsx
> +          <YoutubeParser isOpen={isModalOpen} closeModal={closeModal} />
Да, давай. Тут только ты наверное имел ввиду такой код.
```          {isModalOpen && <YoutubeParser closeModal={closeModal} />}
```

2024-10-22 13:24 UTC, foxprogs requested changes

2024-10-22 13:24 UTC, foxprogs commented on app/components/Modal.tsx
>      <div className="fixed inset-0 z-40 flex items-center justify-center overflow-y-auto bg-black/20">
для чего тут overflow-y-auto

2024-10-22 13:24 UTC, foxprogs commented on app/components/Modal.tsx
> +        {showCloseButton && closeModal && (
вот такие условия мне очень не нравятся. Получается я включаю в компоненте крестик, ставлю showCloseButton а он не показывается. И оказывается что где-то в компоненте есть условие что нужен еще метод. И тут у меня сразу вопросы.
1. А если я передам closeModal (кстати, надо имя дать какое-то другое, может onClose ) - то кнопка не покажется. Ее надо отдельно включать. Короче очень не удобно таким пользоваться. Может так сделать, если есть onClose то это автоматом добавляет крестик? Не знаю, будет немного лучше но не идеально.

2024-10-22 13:24 UTC, foxprogs commented on app/components/Modal.tsx
> +      <div
![изображение](https://github.com/user-attachments/assets/217493af-7c80-409f-b78b-fcf05c34269d)
не красиво получается, скругления нет. 
![изображение](https://github.com/user-attachments/assets/12934958-153a-4b51-b679-a6aea7a906a8)
Вот так надо сделать

2024-10-22 13:24 UTC, foxprogs commented on app/components/YouTubeCard.jsx
> +    <button className="flex h-64 w-64 cursor-pointer flex-col items-center justify-center gap-6 rounded-3xl border border-primary-200 bg-primary-50 transition-colors duration-300 hover:bg-primary-100
вопрос у меня к этому transition. У нас вроде нигде нет такого сейчас. 
А, ну на кнопках есть. Но там 250ms

2024-10-22 13:24 UTC, foxprogs commented on app/components/Modal.tsx
> +            <Image src="/icons/close.svg" alt="Close" width={24} height={24} />
по факту он 20 пикселей потому что ты его зажал за счет фиксированных размеров button и пэддингов

2024-10-22 13:24 UTC, foxprogs commented on app/components/YoutubeParser.tsx
> +                errorMessage={
а для чего ты тут ставишь условие? Не надо тут писать isInvalid ??

2024-10-22 13:24 UTC, foxprogs commented on app/components/YoutubeParser.tsx
> +              <CustomButton color="primary" onClick={handleParseClick}>
![изображение](https://github.com/user-attachments/assets/9a8183d2-fb85-460a-a15d-fe81f5a99f57)
![изображение](https://github.com/user-attachments/assets/8f0a3e3d-e094-4f17-96dd-804a4a133072)
Кнопка серая, и текст внизу серый и крупнее, если это подсказка. А если ошибка - то мелкий. Это не получилось сделать?

2024-10-22 19:18 UTC, DenisArger commented on app/components/YoutubeParser.tsx
> +                errorMessage={
Везде писали условие

2024-10-23 05:34 UTC, Pavel064 approved these changes

2024-10-23 07:39 UTC, Valyukhov commented on app/components/YouTubeParser.tsx
> +                  setIsInvalid(false)
наверное в таком компоненте не сильно производительность улучшится.
Но может менять `setIsInvalid(false)` только когда isInvalid = true?
```
if (isInvalid) {
    setIsInvalid(false)
  }
```

2024-10-23 07:49 UTC, Valyukhov commented on tailwind.config.js
> +            darger: {
а что за darger название, в фигме не нашёл это вместо black?

2024-10-23 07:53 UTC, DenisArger commented on tailwind.config.js
> +            darger: {
@Valyukhov 
это все что касается error

2024-10-23 08:00 UTC, Valyukhov commented on app/components/Modal.tsx
> +    shadow: 'shadow-small',
а почему shadow и width разделены? они же вместе используются.
чтобы в будущем было удобней?

2024-10-23 08:03 UTC, Valyukhov reviewed
есть предложение

2024-10-23 08:05 UTC, Valyukhov commented on tailwind.config.js
> +            darger: {
может danger? как переводится darger

2024-10-23 08:12 UTC, DenisArger commented on tailwind.config.js
> +            darger: {
Да, была опечатка

2024-10-23 08:13 UTC, DenisArger commented on app/components/Modal.tsx
> +    shadow: 'shadow-small',
@Valyukhov да, для  возможности гибкой настройки в будещем

2024-10-23 08:49 UTC, foxprogs requested changes

2024-10-23 08:49 UTC, foxprogs commented on app/components/Modal.tsx
![изображение](https://github.com/user-attachments/assets/e4ce938c-5f6f-4ea4-9c0b-9c40b7dd1011)
не правильно настроил отступы, не должно быть белого вокруг

2024-10-23 08:49 UTC, foxprogs commented on app/components/YouTubeParser.tsx
![изображение](https://github.com/user-attachments/assets/888db6a9-280a-4055-b7ee-02e36500153c)
![изображение](https://github.com/user-attachments/assets/2fca909a-4d53-4afa-a823-b2fa65259bb9)

Что-то не очень нравится мне, что размер прыгает. Может написать Кристине? Я бы сделал размер текста одинаковым...

2024-10-23 08:49 UTC, foxprogs commented on app/components/Modal.tsx
> +        <div className="max-h-[90vh] overflow-y-auto rounded-2xl px-16 py-[52px]">
для чего тут rounded указан?

2024-10-23 08:49 UTC, foxprogs commented on app/components/Modal.tsx
> +        <div className="max-h-[90vh] overflow-y-auto rounded-2xl px-16 py-[52px]">
и Кристина вроде ответила что для confirmation modal 48 должно быть.

2024-10-23 08:49 UTC, foxprogs commented on app/components/YouTubeParser.tsx
Давай сделаем так, сделай одинаковым и напиши Кристине. Если она не успеет ответить а ты все исправишь - зальем так.

2024-10-23 08:49 UTC, foxprogs commented on app/components/YouTubeParser.tsx
> +                  setIsInvalid(false)
Я думаю это можно не писать. Реакт же делает сравнение, если раньше было false и ты ставишь опять false - то ререндера компонента не произойдет. @Valyukhov

2024-10-23 08:49 UTC, foxprogs commented on app/components/YouTubeParser.tsx
> +                    className={`h-6 overflow-hidden ${isInvalid ? 'block' : 'hidden'}`}
не, это не надо. Удаляй оверфлоу, высоту, условия. Вообще весь див тут не нужен

2024-10-23 08:49 UTC, foxprogs commented on app/components/YouTubeParser.tsx
> +                    className={`h-6 overflow-hidden ${isInvalid ? 'block' : 'hidden'}`}
И параграф тоже не нужен

2024-10-23 09:22 UTC, foxprogs commented on app/components/Modal.tsx
> +        className={`relative my-6 max-h-[90vh] ${width} rounded-2xl bg-white ${shadow} overflow-hidden`}
тут my-6 не нужен, как я вижу

2024-10-23 09:29 UTC, merged